/*
 * Copyright (c) 2025 Karagatan LLC.
 * SPDX-License-Identifier: BUSL-1.1
 */

package gluegen

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
)

const generatedFileName = "glue_gen.go"
const generatedHeader = "// Code generated by gluegen. DO NOT EDIT.\n"

type Options struct {
	Dir      string
	Patterns []string
	Write    bool
	Check    bool
}

type Result struct {
	Generated []string
	Removed   []string
}

type listedPackage struct {
	Dir        string
	Name       string
	ImportPath string
	GoFiles    []string
}

type packageSpec struct {
	Dir        string
	Name       string
	ImportPath string
	Types      []string
}

func Generate(opts Options) (Result, error) {
	if opts.Dir == "" {
		opts.Dir = "."
	}
	if len(opts.Patterns) == 0 {
		opts.Patterns = []string{"./..."}
	}

	pkgs, err := listPackages(opts.Dir, opts.Patterns)
	if err != nil {
		return Result{}, err
	}

	var specs []packageSpec
	seen := make(map[string]struct{}, len(pkgs))
	for _, pkg := range pkgs {
		if _, ok := seen[pkg.Dir]; ok {
			continue
		}
		seen[pkg.Dir] = struct{}{}

		spec, ok, err := inspectPackage(pkg)
		if err != nil {
			return Result{}, err
		}
		if ok {
			specs = append(specs, spec)
		}
	}

	var result Result
	for _, pkg := range pkgs {
		path := filepath.Join(pkg.Dir, generatedFileName)
		spec, ok := findSpec(specs, pkg.Dir)
		switch {
		case ok:
			content, err := render(spec)
			if err != nil {
				return result, err
			}
			changed, err := writeOrCheck(path, content, opts.Write, opts.Check)
			if err != nil {
				return result, err
			}
			if changed {
				result.Generated = append(result.Generated, path)
			}
		default:
			removed, err := removeGenerated(path, opts.Write, opts.Check)
			if err != nil {
				return result, err
			}
			if removed {
				result.Removed = append(result.Removed, path)
			}
		}
	}

	sort.Strings(result.Generated)
	sort.Strings(result.Removed)
	return result, nil
}

func listPackages(dir string, patterns []string) ([]listedPackage, error) {
	args := append([]string{"list", "-json"}, patterns...)
	cmd := exec.Command("go", args...)
	cmd.Dir = dir
	out, err := cmd.Output()
	if err != nil {
		if ee, ok := err.(*exec.ExitError); ok {
			return nil, fmt.Errorf("go list failed: %s", strings.TrimSpace(string(ee.Stderr)))
		}
		return nil, err
	}

	dec := json.NewDecoder(bytes.NewReader(out))
	var pkgs []listedPackage
	for dec.More() {
		var pkg listedPackage
		if err := dec.Decode(&pkg); err != nil {
			return nil, fmt.Errorf("decode go list output: %w", err)
		}
		if pkg.Dir == "" || pkg.Name == "" {
			continue
		}
		pkgs = append(pkgs, pkg)
	}
	return pkgs, nil
}

func inspectPackage(pkg listedPackage) (packageSpec, bool, error) {
	fset := token.NewFileSet()
	candidates := make(map[string]struct{})

	for _, name := range pkg.GoFiles {
		if name == generatedFileName {
			continue
		}
		filename := filepath.Join(pkg.Dir, name)
		file, err := parser.ParseFile(fset, filename, nil, parser.ParseComments)
		if err != nil {
			return packageSpec{}, false, fmt.Errorf("parse %s: %w", filename, err)
		}

		for _, decl := range file.Decls {
			gen, ok := decl.(*ast.GenDecl)
			if !ok || gen.Tok != token.TYPE {
				continue
			}
			for _, spec := range gen.Specs {
				typeSpec, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}
				structType, ok := typeSpec.Type.(*ast.StructType)
				if !ok {
					continue
				}
				if isComponentCandidate(gen.Doc, typeSpec.Doc, structType) {
					candidates[typeSpec.Name.Name] = struct{}{}
				}
			}
		}
	}

	if len(candidates) == 0 {
		return packageSpec{}, false, nil
	}

	types := make([]string, 0, len(candidates))
	for name := range candidates {
		types = append(types, name)
	}
	sort.Strings(types)

	return packageSpec{
		Dir:        pkg.Dir,
		Name:       pkg.Name,
		ImportPath: pkg.ImportPath,
		Types:      types,
	}, true, nil
}

func isComponentCandidate(genDoc, typeDoc *ast.CommentGroup, structType *ast.StructType) bool {
	if hasGlueMarker(genDoc) || hasGlueMarker(typeDoc) {
		return true
	}
	for _, field := range structType.Fields.List {
		if hasGlueTag(field.Tag) || isGlueEmbeddedType(field) {
			return true
		}
	}
	return false
}

func hasGlueMarker(group *ast.CommentGroup) bool {
	if group == nil {
		return false
	}
	for _, comment := range group.List {
		text := strings.TrimSpace(strings.TrimPrefix(comment.Text, "//"))
		if strings.HasPrefix(text, "glue:component") ||
			strings.HasPrefix(text, "glue:factory") ||
			strings.HasPrefix(text, "glue:scanner") {
			return true
		}
	}
	return false
}

func hasGlueTag(tag *ast.BasicLit) bool {
	if tag == nil {
		return false
	}
	value := tag.Value
	return strings.Contains(value, `inject:"`) || strings.Contains(value, `value:"`)
}

func isGlueEmbeddedType(field *ast.Field) bool {
	if len(field.Names) > 0 {
		return false
	}
	switch expr := field.Type.(type) {
	case *ast.Ident:
		return isGlueTypeName(expr.Name)
	case *ast.SelectorExpr:
		return isGlueTypeName(expr.Sel.Name)
	default:
		return false
	}
}

func isGlueTypeName(name string) bool {
	switch name {
	case "FactoryBean", "ContextFactoryBean", "Scanner":
		return true
	default:
		return false
	}
}

func findSpec(specs []packageSpec, dir string) (packageSpec, bool) {
	for _, spec := range specs {
		if spec.Dir == dir {
			return spec, true
		}
	}
	return packageSpec{}, false
}

func render(spec packageSpec) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString(generatedHeader)
	buf.WriteString("\n")
	buf.WriteString("package ")
	buf.WriteString(spec.Name)
	buf.WriteString("\n\n")
	buf.WriteString("import \"go.arpabet.com/glue\"\n\n")
	buf.WriteString("type glueGen struct{}\n\n")
	buf.WriteString("func (g *glueGen) ScannerBeans() []any {\n")
	buf.WriteString("\treturn []any{\n")
	for _, typ := range spec.Types {
		buf.WriteString("\t\tnew(")
		buf.WriteString(typ)
		buf.WriteString("),\n")
	}
	buf.WriteString("\t}\n")
	buf.WriteString("}\n\n")
	buf.WriteString("func GlueGen() glue.Scanner {\n")
	buf.WriteString("\treturn &glueGen{}\n")
	buf.WriteString("}\n")

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated %s: %w", spec.ImportPath, err)
	}
	return formatted, nil
}

func writeOrCheck(path string, content []byte, write bool, check bool) (bool, error) {
	current, err := os.ReadFile(path)
	if err == nil && bytes.Equal(current, content) {
		return false, nil
	}
	if err != nil && !os.IsNotExist(err) {
		return false, err
	}
	if check {
		return false, fmt.Errorf("generated file is stale: %s", path)
	}
	if !write {
		return false, nil
	}
	if err := os.WriteFile(path, content, 0o644); err != nil {
		return false, err
	}
	return true, nil
}

func removeGenerated(path string, write bool, check bool) (bool, error) {
	content, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return false, nil
	}
	if err != nil {
		return false, err
	}
	if !bytes.HasPrefix(content, []byte(generatedHeader)) {
		return false, nil
	}
	if check {
		return false, fmt.Errorf("stale generated file should be removed: %s", path)
	}
	if !write {
		return false, nil
	}
	if err := os.Remove(path); err != nil {
		return false, err
	}
	return true, nil
}
